language: python
python:
 - "3.6"
cache: pip
before_install:
 - easy_install distribute
install:
 - pip install pycodestyle
 - pip install -r requirements.txt
 - pip install pandas
 - pip install matplotlib
script:
 - pycodestyle "Graphing Gyroscopes and Linear Acceleration".py

